const USEFUL_LINKS=[['flights',[['Google Flights','https://www.google.com/travel/flights?gl=US&hl=en-US'],['Skyscanner','https://www.skyscanner.com/'],['Kayak','https://www.kayak.com/flights/'],['Alice','https://www.alice.co.il/'],['Kiwi.com','https://www.kiwi.com/'],['Momondo','https://www.momondo.com/']]],['stays',[['Booking.com','https://www.booking.com/'],['Hotels.com','https://www.hotels.com/'],['Airbnb','https://www.airbnb.com/'],['Agoda','https://www.agoda.com/'],['Expedia','https://www.expedia.com/'],['Hostelworld','https://www.hostelworld.com/']]],['activities',[['Waze','https://www.waze.com/live-map/'],['Google Maps','https://www.google.com/maps'],['Klook','https://www.klook.com/'],['GetYourGuide','https://www.getyourguide.com/'],['TripAdvisor','https://www.tripadvisor.com/'],['Rome2Rio','https://www.rome2rio.com/'],['@allTrailsLink','https://www.alltrails.com/']]]];
USEFUL_LINKS.unshift(['beforeTrip',[['@passportLink','https://www.gov.il/he/departments/population_and_immigration_authority'],['@insuranceLink','https://www.passportcard.co.il/travel-insurance/'],['@airaloLink','https://www.airalo.com/'],['@androidLink','https://support.google.com/pixelphone/answer/16115470?hl=en'],['@iphoneLink','https://support.apple.com/en-us/118669'],['IATA Travel Centre','https://www.iata.org/en/services/compliance/timatic/travel-documentation/','iataExplain'],['Passport Index','https://www.passportindex.org/travel-visa-checker/','indexExplain']]]);
USEFUL_LINKS.push(['afterTrip',[['Lupa','https://www.lupa.co.il/']]]);
function renderLinks(){$('trip-panel').innerHTML=`<h2>${tr('usefulLinks')}</h2><p class="intro">${tr('linksNote')}</p>${USEFUL_LINKS.map(([key,links])=>`<section class="link-section"><h3>${tr(key)}</h3><div class="useful-grid">${links.map(([name,url,explain])=>`<a class="useful-link" href="${url}" target="_blank" rel="noopener noreferrer"><div class="link-text"><b>${name.startsWith('@')?tr(name.slice(1)):name}</b>${explain?`<small>${tr(explain)}</small>`:''}</div><span aria-hidden="true">↗</span></a>`).join('')}</div>${key==='beforeTrip'?`<p class="field-help">${tr('carrierNote')}</p><p class="field-help">${tr('passportNote')}</p><p class="visa-note">${tr('visaCaution')}</p>`:''}</section>`).join('')}`;}
const MAX_FILE=10000000,MAX_TOTAL=50000000;let dbPromise=null,docBusy=false,docRender=0;
function documentsDB(){return dbPromise??=new Promise((resolve,reject)=>{const req=indexedDB.open('vellvia.documents.v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('files',{keyPath:'id'});req.onsuccess=()=>{req.result.onversionchange=()=>{req.result.close();dbPromise=null};resolve(req.result)};req.onerror=()=>{dbPromise=null;reject(req.error)};req.onblocked=()=>{dbPromise=null;reject(Error('blocked'))}});}
async function allDocuments(){const db=await documentsDB();return new Promise((resolve,reject)=>{const tx=db.transaction('files','readonly'),r=tx.objectStore('files').getAll();tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)});}
function mutateDocument(record,remove=false){return documentsDB().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite'),store=tx.objectStore('files');if(remove)store.delete(record.id);else{const r=store.getAll();r.onsuccess=()=>{if(r.result.reduce((s,x)=>s+x.size,0)+record.size>MAX_TOTAL){tx.abort();return;}store.add(record)}}tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('quota'))}));}
const bytesLabel=n=>n<1000000?new Intl.NumberFormat(LANGUAGES[language].locale,{maximumFractionDigits:1}).format(n/1000)+' KB':new Intl.NumberFormat(LANGUAGES[language].locale,{maximumFractionDigits:2}).format(n/1000000)+' MB';
async function fileKind(file){const b=new Uint8Array(await file.slice(0,8).arrayBuffer());if(b[0]===37&&b[1]===80&&b[2]===68&&b[3]===70&&b[4]===45)return'application/pdf';if(b[0]===255&&b[1]===216&&b[2]===255)return'image/jpeg';if([137,80,78,71,13,10,26,10].every((x,i)=>b[i]===x))return'image/png';return null;}
async function renderDocuments(tripId,messageKey=''){
 const token=++docRender,panel=$('trip-panel');panel.innerHTML=`<h2>${tr('documents')}</h2><div class="doc-note">${tr('docNote')}</div><p class="field-help">${tr('caps')}</p><label class="primary add-file" tabindex="0" role="button" for="doc-input">${tr('addFile')}</label><input id="doc-input" type="file" accept="application/pdf,image/jpeg,image/png,.pdf,.jpg,.jpeg,.png" class="file-input"><p id="doc-message" role="status">${tr('loading')}</p><p class="field-help" id="doc-usage"></p><div id="doc-list"></div>`;
 const input=$('doc-input');panel.querySelector('.add-file').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}};input.disabled=docBusy;input.onchange=async()=>{const f=input.files[0];input.value='';if(!f)return;docBusy=true;input.disabled=true;const status=k=>{if($('doc-message'))$('doc-message').textContent=tr(k)};status('savingFile');let result='';try{if(!f.size)result='emptyFile';else if(f.size>MAX_FILE)result='fileBig';else{const type=await fileKind(f);if(!type)result='fileType';else{const all=await allDocuments();if(all.reduce((s,x)=>s+x.size,0)+f.size>MAX_TOTAL)result='totalBig';else{let estimate=null;try{estimate=await navigator.storage?.estimate?.()}catch(e){}if(estimate&&Number.isFinite(estimate.quota)&&Number.isFinite(estimate.usage)&&estimate.quota-estimate.usage<f.size)result='spaceLow';else{if(!estimate)status('spaceUnknown');await mutateDocument({id:crypto.randomUUID(),tripId,name:f.name,type,size:f.size,blob:f.slice(0,f.size,type),addedAt:Date.now()});result='fileSaved'}}}}}catch(e){result='saveFail'}finally{docBusy=false;if(screen==='trip'&&tripTab==='documents'&&currentTrip?.id===tripId)await renderDocuments(tripId,result)}};
 try{const all=await allDocuments();if(token!==docRender||screen!=='trip'||tripTab!=='documents'||currentTrip.id!==tripId)return;$('doc-message').textContent=messageKey?tr(messageKey):'';$('doc-usage').textContent=tr('usage',{used:bytesLabel(all.reduce((s,x)=>s+x.size,0))});const mine=all.filter(d=>d.tripId===tripId);$('doc-list').innerHTML=mine.length?mine.map(d=>`<article class="doc-card"><div><h3>${esc(d.name)}</h3><p>${esc(d.type)} · ${bytesLabel(d.size)}</p></div><div class="doc-actions"><button class="quiet" data-open="${d.id}">${tr('open')}</button><button class="quiet" data-download="${d.id}">${tr('download')}</button><button class="quiet delete-file" data-delete="${d.id}">${tr('delete')}</button></div></article>`).join(''):`<p class="intro">${tr('noDocs')}</p>`;
 panel.querySelectorAll('[data-open]').forEach(btn=>btn.onclick=()=>{const d=mine.find(d=>d.id===btn.dataset.open),url=URL.createObjectURL(d.blob);const w=window.open(url,'_blank');if(w)w.opener=null;else $('doc-message').textContent=tr('openFail');setTimeout(()=>URL.revokeObjectURL(url),600000)});
 panel.querySelectorAll('[data-download]').forEach(btn=>btn.onclick=()=>{const d=mine.find(d=>d.id===btn.dataset.download),url=URL.createObjectURL(d.blob),a=document.createElement('a');a.href=url;a.download=d.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)});
 panel.querySelectorAll('[data-delete]').forEach(btn=>btn.onclick=()=>confirmDelete(mine.find(d=>d.id===btn.dataset.delete),tripId));
 }catch(e){if(token===docRender&&$('doc-message')){$('doc-message').textContent=tr('docFail');input.disabled=true}}
}
function confirmDelete(doc,tripId){const dlg=document.createElement('dialog');dlg.innerHTML=`<h2>${tr('deleteTitle')}</h2><p><b>${esc(doc.name)}</b></p><p>${tr('deleteBody')}</p><div class="dialog-actions"><button id="confirm-delete" class="primary">${tr('deleteConfirm')}</button><button id="cancel-delete" class="quiet">${tr('cancel')}</button></div>`;document.body.append(dlg);dlg.onclose=()=>dlg.remove();dlg.querySelector('#cancel-delete').onclick=()=>dlg.close();dlg.querySelector('#confirm-delete').onclick=async()=>{dlg.querySelector('#confirm-delete').disabled=true;try{await mutateDocument(doc,true);dlg.close();if(screen==='trip'&&tripTab==='documents'&&currentTrip.id===tripId)await renderDocuments(tripId,'fileDeleted')}catch(e){dlg.close();if($('doc-message'))$('doc-message').textContent=tr('saveFail')}};dlg.showModal();}
